import { StyleSheet, Platform } from 'react-native';
import { Colors } from '../../themes/Colors';

const TAB_BG_COLOR = Colors.theme1;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F7',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.theme1,
    paddingTop: Platform.OS === 'ios' ? 48 : 24,
    paddingBottom: 16,
    paddingHorizontal: 16,
  },
  backArrow: {
    color: '#fff',
    fontSize: 28,
    marginRight: 12,
    fontWeight: 'bold',
    marginTop: -2,
  },
  headerTitle: {
      flex: 1,
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 16,
  },
  scrollContent: {
    padding: 14,
  },
  billRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
    marginTop: 8,
  },
  billLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: '#222',
  },
  billValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#222',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#222',
    marginBottom: 8,
    marginTop: 18,
  },
  codBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  codIcon: {
    width: 48,
    height: 48,
    marginRight: 12,
    marginTop: 2,
  },
  codTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#222',
    marginBottom: 2,
  },
  codDesc: {
    fontSize: 11,
    color: '#666',
    marginTop: 2,
  },
  walletBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  walletLogo: {
    width: 36,
    height: 36,
    marginRight: 14,
  },
  walletName: {
    fontSize: 15,
    color: '#222',
    fontWeight: '500',
  },
  cardsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 18,
    marginBottom: 8,
  },
  addCard: {
    color: '#1DB954',
    fontWeight: '600',
    fontSize: 13,
  },
  cardBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  cardLogo: {
    width: 38,
    height: 38,
    marginRight: 14,
  },
  cardType: {
    fontSize: 14,
    fontWeight: '700',
    color: '#222',
    marginBottom: 2,
  },
  cardHolder: {
    fontSize: 11,
    color: Colors.GRAY8,
    marginBottom: 1,
  },
  cardExpiry: {
    fontSize: 11,
    color: Colors.GRAY8,
  },
  editCard: {
    color: TAB_BG_COLOR,
    fontWeight: '600',
    fontSize: 14,
    marginLeft: 7,
  },
  continueBtn: {
    backgroundColor: Colors.theme1,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: -2 },
    marginVertical: 5,
    width: '90%',
    alignSelf: 'center',
  },
  continueBtnText: {
    color: Colors.WHITE1,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
});