import { Vector } from '../assets/vector/vector.icon';

export const AppImages = {
  PROFILE: require('../assets/images/profile.jpeg'),
  landing: require('../assets/images/landing.png'),
  Vector1: require('../assets/images/vector.png'),
  dicount: require('../assets/images/discount.png'),
  cred: require('../assets/images/cred.png'),
  filter: require('../assets/images/filter.png'),
  setting: require('../assets/images/setting.png'),
  remove: require('../assets/images/remove.png'),
  cod: require('../assets/images/cod.png'),
  edit: require('../assets/images/edit.png'),
  location: require('../assets/images/location.png'),
  jlogo1: require('../assets/images/jlogo1.png'),
  jsearch: require('../assets/images/jsearch.png'),
  jlogo: require('../assets/images/jlogo.png'),
  jmenu: require('../assets/images/jmenu.png'),
  jcart: require('../assets/images/jcart.png'),
  jnotification: require('../assets/images/jnotification.png'),
  jbag: require('../assets/images/jbag.png'),
  jearing: require('../assets/images/jearing.png'),
  jpinkear: require('../assets/images/jpinkear.jpg'),
  jring: require('../assets/images/jring.png'),
  jmangalsutra: require('../assets/images/jmangalsutra.png'),
  jnecklace: require('../assets/images/jnecklace.png'),
  jchain: require('../assets/images/jchain.png'),
  jbrace: require('../assets/images/jbrace.png'),
  homess: require('../assets/images/homess.png'),
  jdown: require('../assets/images/jdown.png'),
  jwel: require('../assets/images/jwel.jpg'),
  jwel1: require('../assets/images/jwel1.jpg'),
  jwel2: require('../assets/images/jwel2.png'),
  jwel3: require('../assets/images/jwel3.jpg'),
  jwel4: require('../assets/images/jwel4.jpg'),
  jwel5: require('../assets/images/jwel5.png'),
  sad: require('../assets/images/sad.png')
};
