import { Vector } from '../assets/vector/vector.icon';

export const AppImages = {
  LOGO: require('../assets/images/logo.png'),
  LOGO_2: require('../assets/images/logo-2.png'),
  BG_IMAGE: require('../assets/images/bg-image.png'),
  PROFILE: require('../assets/images/profile.jpeg'),
  CLEAN: require('../assets/images/clean.jpg'),
  CLEAN2: require('../assets/images/clean2.jpg'),
  CLEAN3: require('../assets/images/clean3.jpg'),
  CLEAN4: require('../assets/images/clean4.jpeg'),
  background: require('../assets/images/background.jpg'),
  background1: require('../assets/images/background1.png'),
  cloth: require('../assets/images/cloth.png'),
  grocery: require('../assets/images/grocery.png'),
  landing: require('../assets/images/landing.png'),
  gift: require('../assets/images/giftbox.png'),
  Vector1: require('../assets/images/vector.png'),
  fencing: require('../assets/images/fencing.png'),
  girl: require('../assets/images/girl.png'),
  shop: require('../assets/images/shop.png'),
  dicount: require('../assets/images/discount.png'),
  shirt: require('../assets/images/shirt.png'),
  blackT: require('../assets/images/blackT.png'),
  suit: require('../assets/images/suit.png'),
  jeans: require('../assets/images/jeans.png'),
  raymond: require('../assets/images/raymond.png'),
  levis: require('../assets/images/levis.png'),
  gucci: require('../assets/images/gucci.png'),
  peter: require('../assets/images/peter.png'),
  filter: require('../assets/images/filter.png'),
  all: require('../assets/images/all.png'),
  Fshirt: require('../assets/images/Fshirt.png'),
  Fpant: require('../assets/images/Fpant.png'),
  skirt: require('../assets/images/skirt.png'),
  setting: require('../assets/images/setting.png'),
avatar: require('../assets/images/avatar.jpg'),
wishlist: require('../assets/images/wishlist.png'),
remove: require('../assets/images/remove.png'),
cod: require('../assets/images/cod.png'),
edit: require('../assets/images/edit.png')
};
